### ISSUE TITLE
Split the react app.js into components & have them render conditionaly 

### ISSUE THREAD

**Issue by ottotsuma** [ottotsuma/SoloMVP#11]

**Comment by stefanuslim** [comment]
Hi, can I collaborate in this issue? Thanks

**Comment by ottotsuma** [comment]
Hey @stefanuslim , feel free to do so! You can fork and clone any time :) if you need anything feel free to reach out I am usually doing OSS on Friday 9am ~ Japanese time.

**Comment by ottotsuma** [comment]
Hey @stefanuslim , I don't know if you were able to see my comments on your pull request but would you mind if I added you to the readme as a contributor?

**Comment by stefanuslim** [comment]
Hi, sorry for late reply, sure
